### ISSUE TITLE
Change npm instructions according to latest asciidoctor.js changes

### ISSUE THREAD

**Issue by obilodeau** [asciidoctor/asciidoctor-reveal.js#119]
Our current build script will not work with asciidoctor.js > 1.5.5-3 because of an API change. See https://github.com/asciidoctor/asciidoctor.js/issues/269. Luckily our current instructions pin a specific version so this is not an urgent issue.

Error generated:
```
$ node build.js 
/home/olivier/src/asciidoc/presentation-asciidoctorjs-test/build.js:3
var Asciidoctor = asciidoctor.Asciidoctor();
                              ^

TypeError: asciidoctor.Asciidoctor is not a function
    at Object.<anonymous> (/home/olivier/src/asciidoc/presentation-asciidoctorjs-test/build.js:3:31)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

**Comment by obilodeau** [comment]
Pretty sure this is fixed already in master. Anyway, #143 will put the nail in the coffin. Closing.
