### ISSUE TITLE
Ruby custom macros support in v5.0.0

### ISSUE THREAD

**Issue by bcouetil** [asciidoctor/asciidoctor-reveal.js#465]
Will ruby custom macros still be supported in v5 ?

In v4 and earlier, I used some ruby macros such as [c3js and word-cloud](https://github.com/Zenika/adoc-presentation-model/tree/master/docs/lib). We already talked a bit about this subject in #233.

I installed v5.0.0-rc1. Now when using these lauching parameters below :

```
    -r ${PWD}/framework/lib/c3js-block-macro.rb \
    -r ${PWD}/framework/lib/cloud-block-macro.rb \
```

I have this error :

```
/mnt/c/workspace/zenika/formasciidoc/build-docs/framework/lib/c3js-block-macro.rb:1
RUBY_ENGINE == 'opal' ? (require 'c3js-block-macro/extension') : (require_relative 'c3js-block-macro/extension')
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected string
    at Module._compile (internal/modules/cjs/loader.js:893:18)
    at Module._compile (pkg/prelude/bootstrap.js:1285:32)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Module.require (internal/modules/cjs/loader.js:850:19)
    at Module.require (pkg/prelude/bootstrap.js:1229:31)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Function.requireLibrary (/snapshot/asciidoctor-reveal.js/node_modules/@asciidoctor/cli/lib/invoker.js:121:12)
    at /snapshot/asciidoctor-reveal.js/node_modules/@asciidoctor/cli/lib/invoker.js:128:29
```

If this is still supported, I would like an example I could rely on, to make my scripts work :pray:

**Comment by bcouetil** [comment]
Although, I used to put `-r asciidoctor-diagram` to have plantuml diagrams, not it says `MODULE_NOT_FOUND`. I tried removing the parameter, but then plantuml diagrams are not rendered.

**Comment by Mogztter** [comment]
It seems that you are using `-r ${PWD}/framework/lib/c3js-block-macro.rb` with the *Node.js* binary.

You should either use the Ruby gem: https://rubygems.org/gems/asciidoctor-revealjs/versions/5.0.0.rc1 or transpile your Asciidoctor extensions to JavaScript using Opal.

In the future, please direct support questions to the #users stream of the project chat at [asciidoctor.zulipchat.com](https://asciidoctor.zulipchat.com/). Thanks!
